### ISSUE TITLE
Panic error raised by protobuf due to namespace conflict

### ISSUE THREAD

**Issue by sJJdGG** [SagerNet/v2box#1]
input config includes only inbound, outbound and routing objects.

Command:

```
./v2box migrate -c input.json > output.json
```

Error:

```
panic: proto: file "common/log/log.proto" is already registered
        previously from: "github.com/v2fly/v2ray-core/v5/common/log"
        currently from:  "github.com/xtls/xray-core/common/log"
See https://protobuf.dev/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x1a70700?, 0xc000460fc0?}, {0x1a70700?, 0xc000461000})
        /home/admin/go/pkg/mod/google.golang.org/protobuf@v1.30.0/reflect/protoregistry/registry.go:56 +0x1ee
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc000012180, {0x1a96a88?, 0xc00046da40?})
        /home/admin/go/pkg/mod/google.golang.org/protobuf@v1.30.0/reflect/protoregistry/registry.go:130 +0x39f
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x1496fb2, 0x24}, {0x2596d20, 0xc6, 0xc6}, 0x1, 0x0, 0x0, 0x0, {0x1a78d90, ...}, ...})
        /home/admin/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/filedesc/build.go:112 +0x1d6
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x1496fb2, 0x24}, {0x2596d20, 0xc6, 0xc6}, 0x1, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...})
        /home/admin/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/filetype/build.go:138 +0x1b8
github.com/xtls/xray-core/common/log.file_common_log_log_proto_init()
        /home/admin/go/pkg/mod/github.com/xtls/xray-core@v1.8.1-0.20230320070138-172f353bd7fa/common/log/log.pb.go:138 +0x198
github.com/xtls/xray-core/common/log.init.0()
        /home/admin/go/pkg/mod/github.com/xtls/xray-core@v1.8.1-0.20230320070138-172f353bd7fa/common/log/log.pb.go:120 +0x17
```

**Comment by nekohasekai** [comment]
`go build  -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=ignore"`
